### PR TITLE
make it work (JS)

### PR DESCRIPTION
**Pull request by notslang**
the tests fail because `helpers.project.compile` isn't running the hook :confused:

### CODE REVIEW

**Comment by kylemac** [comment]
that is a ton of deletions...

**Comment by slang800** [comment]
yeah, the public folder in the test was being tracked for some reason

**Comment by hhsnopek** [comment]
I left this in such a mess :disappointed: :+1: for fixes!

**Comment by slang800** [comment]
Wait... figured out how to get the tests to pass too :D

**Comment by jenius** [comment]
Thanks for tackling this!

**Comment by hhsnopek** [comment]
So considering @slang800 would like to merge this, before I do could you do this:
- [ ] rename commit 865cf4d (misc)
- [ ] merge 2f81580c73cf883c3b77ff83d42f6379d422b60d & cd96bd90a0a5d7fd69ab17180d8d729bc4842b93

My understanding is that it works, when running `roots compile` on the test case it. The tests are failing for unknown reasons. (cc @slang800)

**Comment by hhsnopek** [comment]
Alright I personally tested the test and it does compile the javascript from component and place it in a build file. Going to go ahead and merge this.

Tests still fail see: https://github.com/carrot/roots-component/issues/1

**Pull request merged**
